### ISSUE TITLE
Language Features Implementation Roadmap

### ISSUE THREAD

**Issue by krvital** [Aidbox/aidbox-sdk#17]
This roadmap outlines the upcoming features and their implementation status for C#, Python, Java, and TypeScript. Please see below for details.

### C#
- [x] General SDK Files including CRUD client and configuration
- [x] Datatype class
- [x] Resource class
- [x] Constraint class
- [x] Polymorphic element representation

### Python
- [ ] General SDK Files including CRUD client and configuration
- [ ] Datatype class
- [ ] Resource class
- [ ] Constraint class
- [ ] Polymorphic element representation

### Java
- [ ] General SDK Files including CRUD client and configuration
- [ ] Datatype class
- [ ] Resource class
- [ ] Constraint class
- [ ] Polymorphic element representation

### TypeScript
- [ ] General SDK Files including CRUD client and configuration
- [ ] Datatype class
- [ ] Resource class
- [ ] Constraint class
- [ ] Polymorphic element representation
